#!/usr/bin/env bash
#
# Simple script for loading scripts in a Pico W with Micropython using rshell
# TODO: Rewrite script in Python (tests/rshell_script/pycon.py)

port='/dev/ttyACM0'

# Connect to board 
conn()
{
    rshell --quiet --port "$port"
}

# Connect to board REPL
repl()
{
    rshell --quiet --port "$port" repl
}

# Do a soft reset on the pico (re-run main.py)
softreset()
{
    rshell --quiet --port "$port" repl "
        ~ import machine
        ~ machine.soft_reset()
        ~
        "
}

# Run the passed script in the Pico W
# Note: You need to be in the same directory than the file
run()
{
    file="$1"
    save "$file"

    module=$(python -c "print('$file'.removesuffix('.py'))")
    rshell --quiet --port "$port" repl "
        ~ import $module
        ~ func = ${module}.main if 'main' in ${module}.__dict__ else print
        ~ func()
        ~
        "

}

# Destroy all functions and vars from this script
desc()
{
    unset port

    funcs=(conn clean save show repl remove desc run softreset)
    for func in "${funcs[@]}"
    do
        unset -f "$func"
    done
}

# Save this specified files to the board
save()
{
    # Check https://gitlab.com/-/snippets/2167862
    rshell --quiet --port "$port" cp --recursive --all "$@" /pyboard/
}

# List the contents of a directory
show()
{
    rshell --quiet --port "$port" ls --all --long /pyboard/"$1"
}

# Remove a file from the board
remove()
{
    if [ -z "$1" ]
    then
        echo "No files provide"
        return 1
    fi
    rshell --quiet --port "$port" rm /pyboard/"$1"
}

# Remove ALL files from the board, except for directories
clean()
{
    rshell --quiet --port "$port" rm /pyboard/*
}

main()
{
    if ! command -v rshell &> /dev/null
    then
        echo "pycon: rshell command not found"
        desc
        return 1
    fi
    unset -f main
}

main
